---
- name: Create extra directories relevant for systemd-networkd
  file:
    path: "{{ item | dirname }}"
    state: directory
  loop: "{{ systemd_network_copy_files | map(attribute='dest') | list + ['/etc/systemd/networkd.conf.d/', '/etc/systemd/resolved.conf.d/', '/etc/network/'] }}"

- name: Find existing systemd-network config files
  find:
    paths:
      - /etc/systemd/networkd.conf.d/
      - /etc/systemd/network/
    patterns:
      - "*.conf"
      - "*.netdev"
      - "*.network"
  register: systemd_network_existing_config_files
  when: not systemd_network_keep_existing_definitions

- name: Calculate which systemd-network config files to delete
  set_fact:
    systemd_network_confs_to_delete: >-
      {{
        systemd_network_existing_config_files.files
        | map(attribute='path')
        | select("match", "^/etc/systemd/networkd\.conf\.d/.*\.conf$")
        | map('basename') | map('splitext') | map('first')
        | difference((systemd_network_confs | combine).keys())
      }}
    systemd_network_netdevs_to_delete: >-
      {{
        systemd_network_existing_config_files.files
        | map(attribute='path')
        | select("match", "^/etc/systemd/network/.*\.netdev$")
        | map('basename') | map('splitext') | map('first')
        | difference((systemd_network_netdevs | combine).keys())
      }}
    systemd_network_networks_to_delete: >-
      {{
        systemd_network_existing_config_files.files
        | map(attribute='path')
        | select("match", "^/etc/systemd/network/.*\.network$")
        | map('basename') | map('splitext') | map('first')
        | difference((systemd_network_networks | combine).keys())
      }}
  when: not systemd_network_keep_existing_definitions

- name: Instantiate systemd-networkd networkd.conf drop-ins
  template:
    src: conf.j2
    dest: /etc/systemd/networkd.conf.d/{{ conf.key }}.conf
    owner: systemd-network
    mode: 0640
  loop: "{{ systemd_network_confs | combine | dict2items }}"
  loop_control:
    loop_var: conf
    label: "{{ conf.key }}"
  notify:
    - Reload systemd configuration
    - Restart systemd-networkd service

- name: Instantiate systemd-networkd network devices
  template:
    src: netdev.j2
    dest: /etc/systemd/network/{{ netdev.key }}.netdev
    owner: systemd-network
    mode: 0640
  loop: "{{ systemd_network_netdevs | combine | dict2items }}"
  loop_control:
    loop_var: netdev
    label: "{{ netdev.key }}"
  notify:
    - Reload systemd configuration
    - Restart systemd-networkd service

- name: Instantiate systemd-networkd networks
  template:
    src: network.j2
    dest: /etc/systemd/network/{{ network.key }}.network
    owner: systemd-network
    mode: 0640
  loop: "{{ systemd_network_networks | combine | dict2items }}"
  loop_control:
    loop_var: network
    label: "{{ network.key }}"
  notify:
    - Reload systemd configuration
    - Restart systemd-networkd service

- name: Copy extra files relevant for systemd-networkd
  copy: "{{ item }}"
  loop: "{{ systemd_network_copy_files }}"
  notify:
    - Restart systemd-networkd service

- name: Install systemd-resolved
  package:
    name: systemd-resolved
  when: ansible_distribution == 'Debian' and not ansible_distribution_major_version is version('12', '<')

- name: Configure resolv.conf
  file:
    dest: /etc/resolv.conf
    state: link
    src: /run/systemd/resolve/resolv.conf
    force: True
    follow: False

- name: Check if resolvconf service exists
  command: systemctl cat resolvconf.service
  failed_when: resolvconf_service_list.rc not in [0, 1]
  changed_when: False
  register: resolvconf_service_list

- name: Stop, disable, and mask resolvconf
  systemd:
    name: resolvconf
    enabled: False
    masked: True
    state: stopped
  when: resolvconf_service_list.rc == 0

- name: Instantiate systemd-resolved resolved.conf drop-ins
  template:
    src: conf.j2
    dest: /etc/systemd/resolved.conf.d/{{ conf.key }}.conf
    owner: systemd-resolve
    mode: 0640
  loop: "{{ systemd_resolve_confs | combine | dict2items }}"
  loop_control:
    loop_var: conf
    label: "{{ conf.key }}"
  notify:
    - Reload systemd configuration
    - Restart systemd-resolved service

- name: Enable systemd-resolved
  service:
    name: systemd-resolved
    enabled: True
    state: started

- name: Delete existing unwanted network interfaces
  shell: |
    if [ ! -e /sys/class/net/{{ interface_name | quote }} ]; then
      exit 128
    fi
    ip link delete {{ interface_name | quote }}
  # From `man ip`:
  # Exit status is 0 if command was successful, and 1 if there is a syntax error.  If an error was reported by the kernel exit status is 2.
  register: result
  failed_when: result.rc not in [0, 128]
  changed_when: result.rc != 128
  notify:
    - Restart systemd-networkd service
  loop: "{{ systemd_network_netdevs_to_delete }}"
  loop_control:
    loop_var: interface_name
  when: not systemd_network_keep_existing_definitions

- name: Delete existing unwanted systemd-networkd configs
  file:
    state: absent
    path: "{{ path }}"
  notify:
    - Reload systemd configuration
    - Restart systemd-networkd service
  loop: >-
    {{
      systemd_network_confs_to_delete | map('regex_replace', '^', '/etc/systemd/networkd.conf.d/') | map('regex_replace', '$', '.conf')
      +
      systemd_network_netdevs_to_delete | map('regex_replace', '^', '/etc/systemd/network/') | map('regex_replace', '$', '.netdev')
      +
      systemd_network_networks_to_delete | map('regex_replace', '^', '/etc/systemd/network/') | map('regex_replace', '$', '.network')
    }}
  loop_control:
    loop_var: path
  when: not systemd_network_keep_existing_definitions

- meta: flush_handlers

- name: Enable systemd-networkd service
  service:
    name: systemd-networkd
    enabled: True
    state: started

- name: Check if legacy networking exists
  command: systemctl cat networking
  failed_when: networking_service_exists.rc not in [0, 1]
  changed_when: False
  register: networking_service_exists

- name: Disable legacy networking
  systemd:
    name: networking
    enabled: False
    masked: True
    state: stopped
  when: networking_service_exists.rc == 0

- name: Remove content from /etc/network/interfaces
  copy:
    dest: /etc/network/interfaces
    content: |
      # Ansible managed - Do not edit here
      # We do not use legacy networking but systemd-networkd.
      # See /etc/systemd/network/ for the configuration
