---
- name: Find existing systemd-network config files
  find:
    paths: /etc/systemd/network/
    patterns:
      - "*.netdev"
      - "*.network"
  register: systemd_network_existing_config_files

- name: Calculate which systemd-network config files to delete
  set_fact:
    systemd_network_config_files_to_delete: >-
      {{ systemd_network_existing_config_files.files
          | map(attribute='path')
          | difference(systemd_network_netdevs.keys()
            | map('regex_replace', '^', '/etc/systemd/network/')
            | map('regex_replace', '$', '.netdev')
            | union(systemd_network_networks.keys()
              | map('regex_replace', '^', '/etc/systemd/network/')
              | map('regex_replace', '$', '.network')
            )
          )
      }}

- name: Delete existing unwanted systemd-networkd configs
  file:
    state: absent
    path: "{{ config_file }}"
  loop: "{{ systemd_network_config_files_to_delete }}"
  loop_control:
    loop_var: config_file
  notify:
    - Reload systemd configuration
    - Restart systemd-networkd service
  when: not systemd_network_keep_existing_definitions

- name: Instantiate systemd-networkd network devices
  template:
    src: netdev.j2
    dest: /etc/systemd/network/{{ netdev.key }}.netdev
    owner: systemd-network
    mode: 0640
  loop: "{{ systemd_network_netdevs | dict2items }}"
  loop_control:
    loop_var: netdev
  notify:
    - Reload systemd configuration
    - Restart systemd-networkd service

- name: Instantiate systemd-networkd networks
  template:
    src: network.j2
    dest: /etc/systemd/network/{{ network.key }}.network
    owner: systemd-network
    mode: 0640
  loop: "{{ systemd_network_networks | dict2items }}"
  loop_control:
    loop_var: network
  notify:
    - Reload systemd configuration
    - Restart systemd-networkd service

- name: Create extra directories relevant for systemd-networkd
  file:
    path: "{{ item | dirname }}"
    state: directory
  loop: "{{ systemd_network_copy_files | map(attribute='dest') | list }}"

- name: Copy extra files relevant for systemd-networkd
  copy: "{{ item }}"
  loop: "{{ systemd_network_copy_files }}"
  notify:
    - Restart systemd-networkd service

- name: Configure resolv.conf
  file:
    dest: /etc/resolv.conf
    state: link
    src: "{{ _systemd_network_resolv_conf_paths[systemd_network_dns_resolver] }}"
    force: True
    follow: False

- name: Populate service facts
  service_facts: {}

- name: Disable unwanted resolvers
  service:
    name: "{{ item }}"
    enabled: False
    state: stopped
  when: "(item + '.service') in ansible_facts.services"
  loop: "{{ _systemd_network_resolv_conf_paths.keys() | difference([systemd_network_dns_resolver]) }}"

- name: Enable wanted resolver
  service:
    name: "{{ systemd_network_dns_resolver }}"
    enabled: True
    state: started

- meta: flush_handlers

- name: Enable systemd-networkd service
  service:
    name: systemd-networkd
    enabled: True
    state: started

- name: Disable legacy networking
  service:
    name: networking
    enabled: False
    state: stopped

- name: Remove /etc/network/interfaces
  file:
    path: /etc/network/interfaces
    state: absent
