---
- name: Instantiate systemd-networkd network devices
  template:
    src: netdev.j2
    dest: /etc/systemd/network/{{ netdev.key }}.netdev
    owner: systemd-network
    mode: 0640
  loop: "{{ systemd_network_netdevs | dict2items }}"
  loop_control:
    loop_var: netdev
  notify:
    - Reload systemd configuration
    - Configure network services

- name: Instantiate systemd-networkd networks
  template:
    src: network.j2
    dest: /etc/systemd/network/{{ network.key }}.network
    owner: systemd-network
  loop: "{{ systemd_network_networks | dict2items }}"
  loop_control:
    loop_var: network
  notify:
    - Reload systemd configuration
    - Configure network services

- name: Create extra directories relevant for systemd-networkd
  file:
    path: "{{ item | dirname }}"
    state: directory
  loop: "{{ systemd_network_copy_files | map(attribute='dest') | list }}"

- name: Copy extra files relevant for systemd-networkd
  copy: "{{ item }}"
  loop: "{{ systemd_network_copy_files }}"
  notify:
    - Configure network services

- name: Configure resolv.conf
  file:
    dest: /etc/resolv.conf
    state: link
    src: "{{ _systemd_network_resolv_conf_paths[systemd_network_dns_resolver] }}"
    force: True
  notify:
    - Configure resolver
