---
- name: Create systemd service for smartmon
  copy:
    dest: /etc/systemd/system/smartmon.service
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Run SMART monitoring script as root

      [Service]
      Type=oneshot
      ExecStart=/bin/bash -c '/home/rojost/smartmon.sh > /tmp/smart.txt && mv /tmp/smart.txt /var/lib/node_exporter/smart.txt'

  notify: Reload systemd configuration

- name: Create systemd timer for smartmon
  copy:
    dest: /etc/systemd/system/smartmon.timer
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Run SMART monitoring script every minute

      [Timer]
      OnBootSec=1min
      OnUnitActiveSec=1min
      AccuracySec=10s
      Persistent=true

      [Install]
      WantedBy=timers.target

  notify: Reload systemd configuration

- name: Enable and start smartmon.timer
  systemd:
    name: smartmon.timer
    enabled: true
    state: started

- meta: flush_handlers
